# Generated by Django 6.0 on 2026-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
    ]
