# Generated by Django 6.0 on 2026-01-29 12:11

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='products/no-img-knit.png', null=True, upload_to='products/'),
        ),
    ]
