# Generated by Django 6.0 on 2026-01-31 16:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='products/no-img-knit.jpg', null=True, upload_to='products/'),
        ),
    ]
