# Generated by Django 6.0 on 2026-01-31 20:57

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='products/no-img-knit.jpg', upload_to='products/'),
        ),
    ]
