# Generated by Django 6.0 on 2026-01-29 11:03

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_publish_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/default-portrait.png', null=True, upload_to='blog_pics/'),
        ),
    ]
