# Generated by Django 6.0 on 2026-01-31 16:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/default-portrait.jpg', null=True, upload_to='blog_pics/'),
        ),
    ]
