# Generated by Django 6.0 on 2026-01-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_country_alter_userprofile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default-portrait.svg', null=True, upload_to='profile_pics/'),
        ),
    ]
