# Generated by Django 6.0 on 2026-01-27 21:33

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/default-portrait.svg', null=True, upload_to='profile_pics/'),
        ),
    ]
