# Generated by Django 6.0 on 2026-01-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_delivery_cost_alter_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
